#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
data:
  values.yaml :  #@ base64.encode(yaml.encode({"ceip_policy_disclosed":True,  "api_ingress":{"fqdn":"api." + data.values.tapIngressDomain,"tls": { "namespace":"tap-install", "secret_name": "taptlscert" }},"app_ingress":{"default_domain":data.values.tapIngressDomain,"tls":{"namespace":"tap-install","secret_name":"taptlscert"}},"app_registry":{"credentials":{"secret_name":"user-registry-dockerconfig", "namespace":"tap-install"},"repository_prefix":data.values.harborUrl + "/tas-adapter/"},"admin":{"users":["tas-admin"]}}))
kind: Secret
metadata:
  name: tas-adapter-tap-install-values
  namespace: tap-install
type: Opaque
